server:
 port: 8080


spring:
 datasource:
  url: jdbc:mysql://localhost:3306/phrase?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate.ddl-auto: create
  generate-ddl: true
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect